version: "3.8"
services:
  udagram-api-feed:
    build: 
      context: ./udagram-api-feed
    image: udagram-api-feed
    ports: 
      - "8091:8091"
    environment:
      POSTGRES_USERNAME:
      POSTGRES_PASSWORD:
      POSTGRES_HOST:
      POSTGRES_DB:
      AWS_BUCKET:
      AWS_REGION:
      AWS_PROFILE:
      JWT_SECRET:
      URL:
    volumes:
      - $HOME/.aws:/root/.aws

  udagram-api-users:
    build: 
      context: ./udagram-api-users
    image: udagram-api-users
    ports: 
      - "8090:8090"
    environment:
      POSTGRES_USERNAME:
      POSTGRES_PASSWORD:
      POSTGRES_HOST:
      POSTGRES_DB:
      AWS_BUCKET:
      AWS_REGION:
      AWS_PROFILE:
      JWT_SECRET:
      URL:

  udagram-frontend:
    build: 
      context: ./udagram-frontend
    image: udagram-frontend
    network_mode: "host"

  udagram-reverseproxy:
    build: 
      context: ./udagram-reverseproxy
    image: udagram-reverseproxy
    ports: 
      - "8080:8080"


  
