version: "3.8"
services:
  udagram-api-feed:
    build: 
      context: ./udagram-api-feed
    image: udagram-api-feed
    # network_mode: "host"
    ports: 
      - "8091:8091"
    environment:
      POSTGRES_USERNAME:
      POSTGRES_PASSWORD:
      POSTGRES_HOST:
      POSTGRES_DB:
      AWS_BUCKET:
      AWS_REGION:
      AWS_PROFILE:
      JWT_SECRET:
      URL:

  udagram-api-users:
    build: 
      context: ./udagram-api-users
    image: udagram-api-users
    # network_mode: "host"
    ports: 
      - "8090:8090"
    environment:
      POSTGRES_USERNAME:
      POSTGRES_PASSWORD:
      POSTGRES_HOST:
      POSTGRES_DB:
      AWS_BUCKET:
      AWS_REGION:
      AWS_PROFILE:
      JWT_SECRET:
      URL:

  udagram-frontend:
    build: 
      context: ./udagram-frontend
    image: udagram-frontend
    network_mode: "host"
    # ports: 
    #   - "8100:8100"
    environment:
      POSTGRES_USERNAME:
      POSTGRES_PASSWORD:
      POSTGRES_HOST:
      POSTGRES_DB:
      AWS_BUCKET:
      AWS_REGION:
      AWS_PROFILE:
      JWT_SECRET:
      URL:

  udagram-reverseproxy:
    build: 
      context: ./udagram-reverseproxy
      network: host
    image: udagram-reverseproxy
    # network_mode: "host"
    ports: 
      - "8080:8080"


  
