version: "3.8"
services:
  feed:
    build: 
      context: ./udagram-api-feed
    image: udagram-api-feed
    network_mode: "host"
    environment:
      POSTGRES_USERNAME:
      POSTGRES_PASSWORD:
      POSTGRES_HOST:
      POSTGRES_DB:
      AWS_BUCKET:
      AWS_REGION:
      AWS_PROFILE:
      JWT_SECRET:
      URL:

  users:
    build: 
      context: ./udagram-api-users
    image: udagram-api-users
    network_mode: "host"
    environment:
      POSTGRES_USERNAME:
      POSTGRES_PASSWORD:
      POSTGRES_HOST:
      POSTGRES_DB:
      AWS_BUCKET:
      AWS_REGION:
      AWS_PROFILE:
      JWT_SECRET:
      URL:

  frontend:
    build: 
      context: ./udagram-frontend
    image: udagram-frontend
    network_mode: "host"
    environment:
      POSTGRES_USERNAME:
      POSTGRES_PASSWORD:
      POSTGRES_HOST:
      POSTGRES_DB:
      AWS_BUCKET:
      AWS_REGION:
      AWS_PROFILE:
      JWT_SECRET:
      URL:

  reverseproxy:
    build: 
      context: ./udagram-reverseproxy
      network: host
    image: udagram-reverseproxy
    network_mode: "host"


  
